name: Creation of Release Version
on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Create Release  
    runs-on: ubuntu-latest
    steps:
      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch 
          incrementPerCommit: false
          github_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Next Release Number
        run: echo ${{ steps.versioning.outputs.version }} 
        
      - name: sync to s3
#         uses: actions/checkout@master
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1' 
          SOURCE_DIR: 'Public' 
          DEST_DIR: 'Public'

